language: r
cache: packages
r_binary_packages:
- covr
- lintr
r:
- release
- devel
after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'devtools::install_github("hafen/lazyrmd@jsonp"); packagedocs::deploy_travis()'
branches:
  only:
  - master
  - dev
